//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by remotecpu.rc
//
#define IDNEXT                          3
#define IDCANCELALL                     3
#define IDCANCELTHIS                    4
#define IDI_CHECKBOX_UNCHECKED          5
#define ID_PARSE_MAP_FILE               5
#define ID_GET_MAP_FILE                 6
#define IDD_REMOTECPU_DIALOG            102
#define IDB_LOGO                        139
#define IDB_BITMAP1                     142
#define IDB_GREENSQR                    143
#define IDB_BLUESQR                     144
#define IDR_MENU_PROCESS                145
#define IDR_MENU_THREAD                 146
#define IDI_CHECKBOX_CHECKED            147
#define IDD_THREAD_PRIORITY             149
#define IDD_START_PROCESS               150
#define IDC_FINGER                      151
#define IDD_ABOUT                       153
#define IDD_DEVICE                      154
#define IDD_OPTIONS                     155
#define IDR_HTML1                       161
#define IDR_HTML2                       162
#define IDR_HTML3                       163
#define IDR_CSS                         164
#define IDR_PLOT_JS                     165
#define IDR_RAPHAEL_JS                  166
#define IDR_HEADERBG_PNG                167
#define IDR_PBG_PNG                     168
#define IDR_LOGO_PNG                    169
#define IDB_LISTICON                    175
#define IDD_DEBUG_PROCESS               178
#define IDD_WATCH                       178
#define IDB_SKULL                       179
#define IDD_DEBUG_PROCESS2              181
#define IDD_DEBUG_PROCESS3              182
#define IDD_DEBUG_PROCESS1              183
#define IDD_DEBUG_PROCESS_INFO          184
#define IDD_DEBUG_PROCESS_ALERT         184
#define IDD_MEMORY_WATCH                185
#define IDD_MEMORY_WATCH_ALERT          186
#define IDD_CPU_WATCH                   187
#define IDD_CPU_WATCH_ALERT             188
#define IDB_CRASH                       188
#define IDB_ALERT                       189
#define IDD_CPU_WATCH1                  189
#define IDD_TOTAL_CPU_WATCH             189
#define IDB_SPY                         190
#define IDB_DEVICE                      193
#define IDD_TOTAL_CPU_WATCH_ALERT       198
#define IDD_DIALOG_SAVED                200
#define IDD_ERROR                       201
#define IDI_MAINFRAME                   202
#define IDI_REPORT                      203
#define IDD_PYTHON                      204
#define IDI_PS                          205
#define IDI_TH                          206
#define IDI_WATCH_CPU                   207
#define IDI_WATCH_CRASH                 208
#define IDD_TRIAL_VALIDATION            210
#define IDR_KEY1                        213
#define IDR_PRIVATE_KEY                 213
#define IDB_BITMAP2                     214
#define IDD_CPU_GRAPHS_PROP_PAGE        215
#define IDD_PROCESSES                   216
#define IDD_LOADING_DATA                217
#define IDD_MEM_GRAPH                   218
#define IDD_POWER_GRAPH                 219
#define IDD_GRAPH_BOX                   221
#define IDD_DIALOG1                     223
#define IDD_CORE_GRAPHS                 223
#define IDB_PNG1                        240
#define IDB_BITMAP9                     254
#define IDB_POWER_PLUG_CONNECTED        255
#define IDB_POWER_PLUG_DISCONNECTED     256
#define IDB_POWER_PLUG_TALKING1         257
#define IDB_POWER_PLUG_TALKING2         258
#define IDB_POWER_PLUG_TALKING3         259
#define IDB_POWER_PLUG_TALKING4         260
#define IDB_SNAPSHOT                    262
#define IDB_RESET                       263
#define IDB_REPORT                      264
#define IDB_BATTERY0                    265
#define IDB_BATTERY10                   266
#define IDB_BATTERY20                   267
#define IDB_BATTERY30                   268
#define IDB_BATTERY40                   269
#define IDB_BATTERY50                   270
#define IDB_BATTERY60                   271
#define IDB_BATTERY70                   272
#define IDB_BATTERY80                   273
#define IDB_BATTERY90                   274
#define IDB_BATTERY100                  275
#define IDB_BATTERY_CHARGING            276
#define IDB_GREEN_BAR_GRAPH0            277
#define IDB_GREEN_BAR_GRAPH10           278
#define IDB_GREEN_BAR_GRAPH20           279
#define IDB_GREEN_BAR_GRAPH30           280
#define IDB_GREEN_BAR_GRAPH40           281
#define IDB_GREEN_BAR_GRAPH50           282
#define IDB_GREEN_BAR_GRAPH60           283
#define IDB_GREEN_BAR_GRAPH70           284
#define IDB_GREEN_BAR_GRAPH80           285
#define IDB_GREEN_BAR_GRAPH90           286
#define IDB_GREEN_BAR_GRAPH100          287
#define IDB_PURPLE_BAR_GRAPH0           288
#define IDB_PURPLE_BAR_GRAPH10          289
#define IDB_PURPLE_BAR_GRAPH20          290
#define IDB_PURPLE_BAR_GRAPH30          291
#define IDB_PURPLE_BAR_GRAPH40          292
#define IDB_PURPLE_BAR_GRAPH50          293
#define IDB_PURPLE_BAR_GRAPH60          294
#define IDB_PURPLE_BAR_GRAPH70          295
#define IDB_PURPLE_BAR_GRAPH80          296
#define IDB_PURPLE_BAR_GRAPH90          297
#define IDB_PURPLE_BAR_GRAPH100         298
#define IDI_ICON1                       307
#define IDI_ICON2                       308
#define IDD_SELECT_CORE                 311
#define IDC_EDIT_FOLDER                 1000
#define IDC_EDIT_IP                     1000
#define IDC_BUTTON_BROWSE               1001
#define IDC_EDIT_USER                   1001
#define IDC_EDIT_SEARCHSTRING           1002
#define IDC_EDIT_REPLACESTRING          1003
#define IDC_BUTTON_REPLACE              1004
#define IDC_EDIT_FILEINPROGRESS         1005
#define IDC_EDIT_COUNT                  1006
#define IDC_BUTTON_FIND                 1007
#define IDC_STATIC_2                    1008
#define IDC_STATIC_1                    1009
#define IDC_STATIC_CONNECT              1009
#define IDC_STATIC_TRY_TO_GET_CRASH     1009
#define IDC_CHECK_CASE_SENSITIVE        1010
#define IDC_CHECK_MATCH_WHOLE_WORD      1011
#define IDC_EDIT_CURRENT_FILE           1012
#define IDC_EDIT_PORT                   1013
#define IDC_CHECK_FILTER                1014
#define IDC_EDIT_PASS                   1014
#define IDC_CHECK_USE_SLIST_RLIST       1015
#define IDC_BUTTON_CONNECT              1015
#define IDC_BUTTON_REPORT               1015
#define IDC_BUTTON_RESET                1016
#define IDC_BUTTON_RESET_DEVICE         1016
#define IDC_BUTTON_SUSPEND              1017
#define IDC_BUTTON_KEY                  1017
#define IDC_BUTTON_BROWSE_DATA_FILE     1017
#define IDC_STATIC_IP                   1018
#define IDC_BUTTON_GET__TRIAL_KEY       1018
#define IDC_STATIC_PORT                 1019
#define IDC_BUTTON_RESET3               1019
#define IDC_STATIC_MONITOR              1020
#define IDC_STATIC_USER                 1020
#define IDC_BUTTON_RESET_SERVER         1021
#define IDC_STATIC_PASS                 1021
#define IDC_BUTTON_GET_SNAPSHOT         1022
#define IDC_BUTTON_SAVE_SNAPSHOT        1022
#define IDC_STATIC_CONNECT_MESG         1023
#define IDC_STATIC_SYSTEM_INFO          1024
#define IDC_STATIC_MEMORY_INFO          1025
#define IDC_STATIC_ABOUT                1026
#define IDC_STATIC_SYSTEM_INFO2         1026
#define IDC_STATIC_PROCESSOR_INFO       1026
#define IDC_STATIC_LOGO                 1027
#define IDC_CHECK_SHOW_THREADS          1032
#define IDC_STATIC_THREAD_PRIORITY      1033
#define IDC_BUTTON_SET_SNAPSHOT         1033
#define IDC_BUTTON_CAPTURE_START        1033
#define IDC_EDIT_THREAD_PRIORITY        1034
#define IDC_CHECK_SHOW_MEMORY           1034
#define IDC_EDIT_SNAP_INTERVAL          1035
#define IDC_STATIC_PERIODIC_SNAPSHOTS   1036
#define IDC_STATIC_MAP_FILE             1036
#define IDC_STATIC_DEVICE               1037
#define IDC_STATIC_EMAIL                1037
#define IDC_EDIT_URL1                   1038
#define IDC_STATIC_CEMON_PRIORITY       1038
#define IDC_STATIC_TITLE                1038
#define IDC_STATIC_SNAPSHOT             1039
#define IDC_EDIT_PROCESS_PATH           1039
#define IDC_STATIC_VERSION              1040
#define IDC_EDIT_MAP_FILE_PATH          1040
#define IDC_BUTTON_CAPTURE_STOP         1041
#define IDC_EDIT_EMAIL_TO               1041
#define IDC_EDIT_KEY                    1042
#define IDC_STATIC_KEY                  1043
#define IDC_STATIC_KEY2                 1044
#define IDC_STATIC_KEYSTR               1044
#define IDC_STATIC_MY_MAC               1045
#define IDC_ABOUT                       1046
#define IDC_STATIC_KEY3                 1047
#define IDC_STATIC_MAC                  1047
#define IDC_STATIC_PROPSHEET            1048
#define IDC_STATIC_KEYSTR3              1048
#define IDC_STATIC_MESSAGE              1048
#define IDC_STATIC_MONITOR_PS           1049
#define IDC_STATIC_KEYSTR2              1050
#define IDC_CHECK_CAPTURE_ON_DEV        1051
#define IDC_PROGRESS_LOAD_DATA          1053
#define IDC_STATIC_LOADING_RTM          1054
#define IDC_CHECK_DONT_PROMPT_SHOW_REPORT 1054
#define IDC_BUTTON_LOAD_CAPTURED_DATA   1055
#define IDC_RADIO_DEBUG_ACTIVE_PROCESS  1057
#define IDC_RADIO_DEBUG_NEW_PROCESS     1058
#define IDC_STATIC_PID                  1059
#define IDC_CHECK_RESTART_AFTER_CRASH   1060
#define IDC_CHECK_RESET_DEVICE          1060
#define IDC_STATIC_DBG1                 1061
#define IDC_CHECK_PS_WATCH              1061
#define IDC_KILL_PS                     1061
#define IDC_CHECK_KILL_PS               1061
#define IDC_STATIC_DBG2                 1062
#define IDC_RESTART_PS                  1062
#define IDC_CHECK_RESTART_PS            1062
#define IDC_STATIC_DBG3                 1063
#define IDC_CHECK_SILENT_AFTER_CRASH    1064
#define IDC_STATIC_ENTER_PATH           1065
#define IDPREVIOUS                      1066
#define IDC_EDIT_MESG                   1068
#define IDC_EDIT_MEMORY_LIMIT           1070
#define IDC_EDIT_TIME_LIMIT             1071
#define IDC_STATIC_MEMORY_ALERT_MSG     1073
#define IDC_EDIT_CPU_LIMIT              1074
#define IDC_COMBO_ITEMS                 1075
#define IDC_WATCH_LIST                  1076
#define IDC_STATIC_ALERT_MSG            1077
#define IDC_EDIT_SMTP_SERVER            1078
#define IDC_EDIT_SMTP_PORT              1079
#define IDC_DEVICE                      1080
#define IDC_EDIT_EMAILTO                1080
#define IDC_STATIC_MESG                 1082
#define IDC_CHECK_DO_NOT_PROMPT_AGAIN   1083
#define IDC_STATIC_CALLSTACK_DISCLAIMER 1084
#define IDC_BUTTON_EMAIL_TEST           1085
#define IDC_STATIC_MESG1                1085
#define IDC_BUTTON_LOAD_PY              1087
#define IDC_EDIT_PY                     1088
#define IDC_BUTTON_RUN_PY               1089
#define IDC_CHECK1                      1090
#define IDC_CHECK_RUN_PY_AT_STARTUP     1090
#define IDC_CHECK_PROXY_USE             1090
#define IDC_STATIC_VALIDATE             1092
#define IDC_STATIC_PROXY                1093
#define IDC_EDIT_PY_OUTPUT              1094
#define IDC_STATIC_PY_PATH              1095
#define IDC_EDIT_URL_PYTHON             1096
#define IDC_BUTTON_START_TRIAL          1097
#define IDC_SPLITTER_BUTTON             1097
#define IDC_BUTTON_PURCHASE_LICENSE     1098
#define IDC_SPLIT1                      1098
#define IDC_BUTTON_VALIDATE_KEY         1099
#define IDC_LIST1                       1100
#define IDC_CPU_LEGEND                  1101
#define IDC_STATIC_GRAPH_BOX            1103
#define IDC_BUTTON1                     1104
#define IDC_PLUG                        1105
#define IDC_PLUG2                       1106
#define IDC_BUTTON_SNAPSHOT             1106
#define IDC_CPU_BAR_GRAPH               1107
#define IDC_BUTTON_SNAPSHOT2            1107
#define IDC_MEMORY_BAR_GRAPH            1108
#define IDC_COMBO2                      1108
#define IDC_COMBO_CORE                  1108
#define IDC_COMBO1                      1108
#define IDC_COMBO_CEMONS                1108
#define IDC_BATTERY_BAR_GRAPH           1109
#define IDC_BUTTON_CPU                  1110
#define IDC_BUTTON_BATTERY              1111
#define IDC_BUTTON_MEMORY               1112
#define IDC_BUTTON_CONN                 1113
#define ID_PROCESS_KILL                 32771
#define ID_PROCESS_RESTART              32772
#define ID_PROCESS_PLOT                 32773
#define ID_THREAD_KILL                  32774
#define ID_THREAD_SUSPEND               32775
#define ID_THREAD_RESUME                32776
#define ID_THREAD_PRIORITY              32777
#define ID_THREAD_PLOT                  32778
#define ID_TEST_1                       32779
#define ID_TEST_2                       32780
#define ID_TEST                         32781
#define ID_TEST_3                       32782
#define ID_TEST_4                       32783
#define ID_PROCESS_START                32784
#define ID_PROCESS_CLONE                32785
#define ID_GRAPHLEGENDMENU_REMOVEGRAPH  32787
#define ID_GRAPHLEGENDMENU_CHANGECOLOR  32788
#define ID_CRASH_REPORT                 32790
#define ID_CRASH_WATCH                  32790
#define ID_MEMORY_WATCH                 32791
#define ID_PROCESLISTMENU_CPUWATCH      32792
#define ID_CPU_WATCH                    32793
#define ID_PROCESLISTMENU_CPUWATCH32794 32794
#define ID_TOTAL_CPU_WATCH              32795
#define ID_PLOT_CPU                     32796
#define ID_PLOT_MEM                     32797
#define ID_SELECT_CORE                  32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        313
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
